# Generated by Django 2.1.2 on 2018-12-28 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('ocupada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.TimeField(auto_now=True)),
                ('horaSalida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='boton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorWorker.Sensor'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorWorker.Sensor'),
        ),
    ]
