# Generated by Django 2.1.2 on 2018-12-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorWorker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horaSalida',
            field=models.TimeField(null=True),
        ),
    ]
