# Generated by Django 2.1.2 on 2018-12-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorWorker', '0002_auto_20181227_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horaSalida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
