# Generated by Django 2.1.2 on 2018-12-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorWorker', '0004_auto_20181227_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='boton',
            new_name='sensor',
        ),
    ]
